package UI;

import abstractfactory.FabricaDiscos;
import abstractfactory.FabricaDiscos_CapaSimple;
import abstractfactory.FabricaDiscos_CapaDoble;
import abstractfactory.DVD;
import abstractfactory.BluRay;
import javax.swing.JOptionPane;
/**
 *
 * @author Keons
 */
public class VentanaPrincipal extends javax.swing.JFrame {

   
    FabricaDiscos fabrica;
    BluRay bluRay;
    DVD dvd;
    public VentanaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        botonDVD_S = new javax.swing.JButton();
        botonDVD_D = new javax.swing.JButton();
        botonBlueRay_S = new javax.swing.JButton();
        botonBlueRay_D = new javax.swing.JButton();
        fieldCantidadDiscos = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(11, 11, 11));

        botonDVD_S.setText("DVD Simple");
        botonDVD_S.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDVD_SActionPerformed(evt);
            }
        });

        botonDVD_D.setText("DVD Doble");
        botonDVD_D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDVD_DActionPerformed(evt);
            }
        });

        botonBlueRay_S.setText("BluRay Simple");
        botonBlueRay_S.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBlueRay_SActionPerformed(evt);
            }
        });

        botonBlueRay_D.setText("BluRay Doble");
        botonBlueRay_D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBlueRay_DActionPerformed(evt);
            }
        });

        fieldCantidadDiscos.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fieldCantidadDiscos.setText("1");
        fieldCantidadDiscos.setToolTipText("Cantidad de Discos a comprar");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("Discos a Comprar");

        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(111, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(fieldCantidadDiscos, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(botonDVD_S)
                                .addGap(80, 80, 80)
                                .addComponent(botonDVD_D)))
                        .addGap(91, 91, 91)
                        .addComponent(botonBlueRay_S)
                        .addGap(85, 85, 85)
                        .addComponent(botonBlueRay_D)
                        .addGap(104, 104, 104))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(69, 69, 69))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldCantidadDiscos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonDVD_S)
                    .addComponent(botonDVD_D)
                    .addComponent(botonBlueRay_S)
                    .addComponent(botonBlueRay_D))
                .addGap(36, 36, 36)
                .addComponent(jButton1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private int CalcularPrecio(int cantidad, int precio){        
        int cobro = 0;
        while(cantidad != 0){
            cobro += precio;
            cantidad--;
        }
        return cobro;
    }
    private void botonBlueRay_SActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBlueRay_SActionPerformed
        fabrica = new FabricaDiscos_CapaSimple();
        bluRay = fabrica.crearBluRay();
        int cantidad = Integer.parseInt(fieldCantidadDiscos.getText());
        int cobro = CalcularPrecio(cantidad, bluRay.getPrecio());
        JOptionPane.showConfirmDialog(rootPane,"Discos \n"
                                              +"Tipo: "+bluRay.getNombre()+"\n"
                                              +"Precio: "+bluRay.getPrecio()+"\n"
                                              +"Cantidad: "+cantidad+"\n"
                                              +"Precio Total: "+cobro+"\n\n"
                                              + "¿Desea efectuar la compra?","Efectuar Compra",1,3);
       
        
        
    }//GEN-LAST:event_botonBlueRay_SActionPerformed

    private void botonDVD_SActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDVD_SActionPerformed
        fabrica = new FabricaDiscos_CapaSimple();
        dvd = fabrica.crearDVD();
        int cantidad = Integer.parseInt(fieldCantidadDiscos.getText());
        int cobro = CalcularPrecio(cantidad, dvd.getPrecio());
        JOptionPane.showConfirmDialog(rootPane,"Discos \n"
                                              +"Tipo: "+dvd.getNombre()+"\n"
                                              +"Precio: "+dvd.getPrecio()+"\n"
                                              +"Cantidad: "+cantidad+"\n"
                                              +"Precio Total: "+cobro+"\n\n"
                                              + "¿Desea efectuar la compra?","Efectuar Compra",1,3);
        
    }//GEN-LAST:event_botonDVD_SActionPerformed

    private void botonBlueRay_DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBlueRay_DActionPerformed
        fabrica = new FabricaDiscos_CapaDoble();
        bluRay = fabrica.crearBluRay();
        int cantidad = Integer.parseInt(fieldCantidadDiscos.getText());
        int cobro = CalcularPrecio(cantidad, bluRay.getPrecio());
        JOptionPane.showConfirmDialog(rootPane,"Discos \n"
                                              +"Tipo: "+bluRay.getNombre()+"\n"
                                              +"Precio: "+bluRay.getPrecio()+"\n"
                                              +"Cantidad: "+cantidad+"\n"
                                              +"Precio Total: "+cobro+"\n\n"
                                              + "¿Desea efectuar la compra?","Efectuar Compra",1,3);
    }//GEN-LAST:event_botonBlueRay_DActionPerformed

    private void botonDVD_DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDVD_DActionPerformed
        fabrica = new FabricaDiscos_CapaDoble();
        dvd = fabrica.crearDVD();
        int cantidad = Integer.parseInt(fieldCantidadDiscos.getText());
        int cobro = CalcularPrecio(cantidad, dvd.getPrecio());
        JOptionPane.showConfirmDialog(rootPane,"Discos \n"
                                              +"Tipo: "+dvd.getNombre()+"\n"
                                              +"Precio: "+dvd.getPrecio()+"\n"
                                              +"Cantidad: "+cantidad+"\n"
                                              +"Precio Total: "+cobro+"\n\n"
                                              + "¿Desea efectuar la compra?","Efectuar Compra",1,3);
    }//GEN-LAST:event_botonDVD_DActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonBlueRay_D;
    private javax.swing.JButton botonBlueRay_S;
    private javax.swing.JButton botonDVD_D;
    private javax.swing.JButton botonDVD_S;
    private javax.swing.JTextField fieldCantidadDiscos;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
